version: 0.2
env:
   SPECTRAL_DSN: https://spu-ac9d6e9e4f324b8a84b4547a3c8f5701@spectral-us.checkpoint.com
phases: 
    build: 
        commands: 
            - npm i --save 
    post_build:
        commands:
           - curl -L "https://spectral-eu.checkpoint.com/latest/x/sh?dsn=$SPECTRAL_DSN"| sh
           - SPECTRAL_DSN=https://spu-ac9d6e9e4f324b8a84b4547a3c8f5701@spectral-us.checkpoint.com $HOME/.spectral/spectral scan --ok  --include-tags base,audit
artifacts: 
    files: 
        - "**/*"